base:
  name: test
  output_dir: output
  seed: 524

model:
  type: xgbc
  logr:
    Cs: 10
    cv: 5
    solver: lbfgs
    max_iter: 200
    l1_ratios: [0.0]
  xgbc:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.3
    subsample: 1.0
    colsample_bytree: 1.0

data:
  target_column: target
  date_column: none
  impute_strategy: median

split:
  train_size: 0.8
  test_size: 0.2
  val_size: 0.0
  shuffle: true
  stratified_split: true
  split_column: none
  start_train_date: none
  stop_train_date: none
  start_test_date: none
  stop_test_date: none
  start_val_date: none
  stop_val_date: none
